backend:
  name: github
  repo: capriosa/vuepress-de
  branch: master

public_folder: ".vuepress/dist/"
media_folder: ".vuepress/dist/assets/img"

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sidebar", name: "sidebar", widget: "string",optional:true,default:"auto"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "landingpage"
    label: "Landingpage"  
    folder: "landingpages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Home", name: "home", widget: "string", default:"true"}
      - {label: "Title", name: "title", widget: "string"}
      - { name: actionText, label: 'CTA-Button Text', widget: string }
      - { name: actionLink, label: 'CTA-Button Link', widget: string }
      - { name: pageClass, label: 'Page Class', widget: string }
      widget: "list"
        fields:
          - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
          - label: Author
          name: author
          label: "Features"
          widget: object
            fields:
              - { name: title, label: 'Title', widget: string }
              - { name: details, label: 'Details', widget: text }
        