backend:
  name: github
  repo: capriosa/vuepress-de
  branch: master

public_folder: ".vuepress/dist/"
media_folder: ".vuepress/dist/assets/img"

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sidebar", name: "sidebar", widget: "string",required:false,default:"auto"}
      - {label: "Body", name: "body", widget: "markdown"}

